apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: trickster
  name: trickster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trickster
      name: trickster
    spec:
      containers:
        - name: trickster
          image: trickstercache/trickster:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cfg-volume
              mountPath: /etc/trickster
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: cfg-volume
          configMap:
            name: trickster-conf
            items:
              - key: trickster-conf
                path: trickster.yaml
