matrix:
  include:
  - language: python
    install:
    - pip install codespell
    script:
    - codespell --skip=".git,*.png"

  - language: go
    go:
    - "1.12.x"
    - master
    script:
    - make style test build
