# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.2"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/alicebob/miniredis"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"
